name: Push mkdocs repository

on:
  workflow_dispatch: {}
  # workflow_run: # 自動発火用トリガ
  #   workflows:
  #     - mkdocs build
  #   types: 
  #     - completed                                       # 完了時に実行

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages                             # 使用ブランチ指定

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main

        env:
         # API_TOKEN_GITHUB：Settings→Developer settings→Personal access tokens→Tokens
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

        with:
          source-directory: './'                     # 送り元リポジトリパス
          destination-github-username: 'little-hoge' # ユーザー名
          destination-repository-name: 'mkdocs'      # 送り先リポジトリパス
          user-email: little500ml@gmail.com          # アドレス
          target-branch: main                        # 送り先Brunch

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
